---
- name: Update Host & Install Packet
  hosts: [all]
  become: yes
  roles:
    - { role: update_install, tags: ['update_install'] }

- name: Install Ceph-common
  hosts: [ceph_data]
  become: yes
  roles:
    - { role: install_ceph, tags: ['install_ceph'] }

- name: Deploy Ceph Cluster
  hosts: ceph01
  become: yes
  roles:
    - { role: deploy_cluster, tags: ['deploy_cluster'] }